### ISSUE TITLE
能说下怎么用么？

### ISSUE THREAD

**Issue by yuedingwangji** [ym/icp-query-api#1]
请问用的是工信部的接口么？  还有，请问如何使用呀

**Comment by ym** [comment]
如果你不是 ISP，那么这个项目对你来说没有意义。

这个接口只提供给有 ISP 许可证且和省管局对接过的公司。

**Comment by yuedingwangji** [comment]
原来是这样，我还以为可以查询网站的备案信息呢，还要ISP的许可证 汗
